#!/bin/bash

set -eou pipefail

if ! echo $VERSION | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$"; then
  echo "version invalid"
  exit 1
fi

npm pkg set version=$VERSION
npm install -g yarn

yarn install --immutable --immutable-cache --check-cache
yarn build

npm config set "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN"
npm config set "@${REGISTRY_NAME}:registry=https://npm.pkg.github.com"

npm publish --access public
