#!/bin/bash

set -eou pipefail

npm install -g yarn

yarn install --immutable --immutable-cache --check-cache
yarn build

yarn config set -H \
  "npmRegistries['//npm.pkg.github.com'].npmAuthToken" \
  "$GITHUB_TOKEN"

yarn npm publish --access public
