name: Publish package to github packages
on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0
      - run: scripts/release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_SECRET }}
